spring:
  application:
    name: test-bot-01
  
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    driver-class-name: com.my
  jpa:
    hibernate:
      ddl-auto: update  # 이 설정을 확인하세요
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

logging:
  level:
    root: INFO
    com.tradingview.testbot01: DEBUG