spring:
  application:
    name: test-bot-01
  
  thymeleaf:
    cache: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
#    platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    com.tradingview.testbot01: DEBUG